/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.Assert.*;

import java.util.Arrays;
import java.util.List;
import org.junit.Test;

public class AppTest {

    @Test
    public void testTokenize() {
        String input = "4 * 2 - 1";
        Lexer lexer = new Lexer(input);
        List<Token> tokens = lexer.tokenize();
        Parser parser = new Parser(tokens);
        Expr ex = parser.parse();
        TypeChecker typeChecker = new TypeChecker();
        typeChecker.visit(ex);
        assertEquals("(- (* 4:INT 2:INT):INT 1:INT)", ex.stringify());
    }
}
